package demo.iba.cli;

import demo.iba.mod.Test;
import demo.iba.mod.TestExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST.TEST
     *
     * @mbg.generated Tue Aug 30 19:30:56 KST 2016
     */
    long countByExample(TestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST.TEST
     *
     * @mbg.generated Tue Aug 30 19:30:56 KST 2016
     */
    int deleteByExample(TestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST.TEST
     *
     * @mbg.generated Tue Aug 30 19:30:56 KST 2016
     */
    int deleteByPrimaryKey(BigDecimal no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST.TEST
     *
     * @mbg.generated Tue Aug 30 19:30:56 KST 2016
     */
    int insert(Test record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST.TEST
     *
     * @mbg.generated Tue Aug 30 19:30:56 KST 2016
     */
    int insertSelective(Test record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST.TEST
     *
     * @mbg.generated Tue Aug 30 19:30:56 KST 2016
     */
    List<Test> selectByExample(TestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST.TEST
     *
     * @mbg.generated Tue Aug 30 19:30:56 KST 2016
     */
    Test selectByPrimaryKey(BigDecimal no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST.TEST
     *
     * @mbg.generated Tue Aug 30 19:30:56 KST 2016
     */
    int updateByExampleSelective(@Param("record") Test record, @Param("example") TestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST.TEST
     *
     * @mbg.generated Tue Aug 30 19:30:56 KST 2016
     */
    int updateByExample(@Param("record") Test record, @Param("example") TestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST.TEST
     *
     * @mbg.generated Tue Aug 30 19:30:56 KST 2016
     */
    int updateByPrimaryKeySelective(Test record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST.TEST
     *
     * @mbg.generated Tue Aug 30 19:30:56 KST 2016
     */
    int updateByPrimaryKey(Test record);
}