package demo.iba.mod;

import java.math.BigDecimal;

public class Test {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST.TEST.NO
     *
     * @mbg.generated Tue Aug 30 19:30:56 KST 2016
     */
    private BigDecimal no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST.TEST.NAME
     *
     * @mbg.generated Tue Aug 30 19:30:56 KST 2016
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST.TEST.NO
     *
     * @return the value of TEST.TEST.NO
     *
     * @mbg.generated Tue Aug 30 19:30:56 KST 2016
     */
    public BigDecimal getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST.TEST.NO
     *
     * @param no the value for TEST.TEST.NO
     *
     * @mbg.generated Tue Aug 30 19:30:56 KST 2016
     */
    public void setNo(BigDecimal no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST.TEST.NAME
     *
     * @return the value of TEST.TEST.NAME
     *
     * @mbg.generated Tue Aug 30 19:30:56 KST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST.TEST.NAME
     *
     * @param name the value for TEST.TEST.NAME
     *
     * @mbg.generated Tue Aug 30 19:30:56 KST 2016
     */
    public void setName(String name) {
        this.name = name;
    }
}